# Generated by Django 5.1.3 on 2024-11-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("firstname", models.CharField(max_length=80)),
                ("lastname", models.CharField(max_length=80)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("hubspot_id", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deal_name", models.CharField(max_length=120)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("stage", models.CharField(max_length=80)),
                ("close_date", models.CharField(blank=True, max_length=50, null=True)),
                ("hubspot_id", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
