# Generated by Django 5.1.3 on 2024-11-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainlogin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
